### ISSUE TITLE
Sharing [RangeError: Maximum call stack size exceeded] when 3 or more clients are connected

### ISSUE THREAD

**Issue by vankasteelj** [vankasteelj/frak#167]
```js
network.js:203 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at network.js:203:24
    at new Promise (<anonymous>)
    at Object.getFreePort (network.js:203:12)
    at network.js:206:120
    at new Promise (<anonymous>)
    at Object.getFreePort (network.js:203:12)
    at network.js:206:120
    at new Promise (<anonymous>)
    at Object.getFreePort (network.js:203:12)
    at network.js:206:120
```

This will happen if 3 clients are connected

**Comment by vankasteelj** [comment]
It worked!
